#!/usr/bin/env python
# coding: utf-8


class StandardInput:

    def stdin_string(self):
        self.s=input().rstrip()
        return self.s

    def stdin_integer(self):
        self.n=int(input().rstrip())
        return self.n

    def stdin_array(self):
        self.arr=input().rstrip().split()
        return self.arr

    def stdin_integer_array(self):
        self.arr=map(int,input().rstrip().split())
        return self.arr

def test(arr):
    return arr[0]**2 + arr[1]**2

if __name__ == '__main__':
    obj=StandardInput()
    arr=obj.stdin_integer_array()
    print(test(arr))
